using System;
using System.IO;
using System.Xml;
using System.Xml.Serialization;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace jDownloaderRemoteControlAPI {

    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    [XmlRoot("jdownloader")]
    public partial class jdownloaderPackage {

        /*
            XmlSerializer s = new XmlSerializer(typeof(jdownloader));
            System.IO.TextWriter w = new System.IO.StreamWriter(@"C:\Request.xml");
            s.Serialize(w, new jdownloader());
            w.Close();
    
            XmlSerializer s = new XmlSerializer(typeof(jdownloader));
            jdownloader _jdownloader;
            System.IO.TextReader r = new System.IO.StreamReader("request.xml");
            _jdownloader = (jdownloader)s.Deserialize(r);
            r.Close();

        */
        public static string SerializeToXmlString(object targetInstance)
        {
            string retVal = string.Empty;
            TextWriter writer = new StringWriter();
            XmlSerializer serializer = new XmlSerializer(targetInstance.GetType());
            serializer.Serialize(writer, targetInstance);
            retVal = writer.ToString();
            return retVal;
        }
        public static object DeserializeFromXmlString(string objectXml, Type targetType)
        {
            object retVal = null;
            XmlSerializer serializer = new XmlSerializer(targetType);
            StringReader stringReader = new StringReader(objectXml);
            XmlTextReader xmlReader = new XmlTextReader(stringReader);
            retVal = serializer.Deserialize(xmlReader);
            return retVal;
        }
        
        private package[] packageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("package")]
        public package[] package {
            get {
                return this.packageField;
            }
            set {
                this.packageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class package {
        
        private string package_ETAField;
        
        private string package_linksinprogressField;
        
        private string package_linkstotalField;
        
        private string package_loadedField;
        
        private string package_nameField;
        
        private decimal package_percentField;
        
        private string package_sizeField;
        
        private string package_speedField;
        
        private string package_todoField;
        
        private file[] fileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string package_ETA {
            get {
                return this.package_ETAField;
            }
            set {
                this.package_ETAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string package_linksinprogress {
            get {
                return this.package_linksinprogressField;
            }
            set {
                this.package_linksinprogressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string package_linkstotal {
            get {
                return this.package_linkstotalField;
            }
            set {
                this.package_linkstotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string package_loaded {
            get {
                return this.package_loadedField;
            }
            set {
                this.package_loadedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string package_name {
            get {
                return this.package_nameField;
            }
            set {
                this.package_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal package_percent {
            get {
                return this.package_percentField;
            }
            set {
                this.package_percentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string package_size {
            get {
                return this.package_sizeField;
            }
            set {
                this.package_sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string package_speed {
            get {
                return this.package_speedField;
            }
            set {
                this.package_speedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string package_todo {
            get {
                return this.package_todoField;
            }
            set {
                this.package_todoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("file")]
        public file[] @file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class file {
        
        private string file_hosterField;
        
        private string file_nameField;
        
        private string file_packageField;
        
        private decimal file_percentField;
        
        private string file_speedField;
        
        private string file_statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string file_hoster {
            get {
                return this.file_hosterField;
            }
            set {
                this.file_hosterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string file_name {
            get {
                return this.file_nameField;
            }
            set {
                this.file_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string file_package {
            get {
                return this.file_packageField;
            }
            set {
                this.file_packageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal file_percent {
            get {
                return this.file_percentField;
            }
            set {
                this.file_percentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string file_speed {
            get {
                return this.file_speedField;
            }
            set {
                this.file_speedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string file_status {
            get {
                return this.file_statusField;
            }
            set {
                this.file_statusField = value;
            }
        }
    }
}
